### ISSUE TITLE
teamsApp/extendToM365 error with NotImplementedError

### ISSUE THREAD

**Issue by brijshah2709** [OfficeDev/teams-toolkit#11907]
**Describe the bug**
When using command `teamsApp/extendToM365` the command throws below error.
```
{
  "errorType": "SystemError",
  "source": "Fx-VS",
  "name": "NotImplementedError",
  "message": "Not implement the method: M365 get token scopes: https://titles.msit.mos.microsoft.com/.default",
  "stack": null,
  "innerError": null,
  "userData": null,
  "timestamp": "2024-06-25T08:44:10.6188838-07:00",
  "displayMessage": "Not implement the method: M365 get token scopes: https://titles.msit.mos.microsoft.com/.default",
  "helpLink": null,
  "issueLink": null
}
```

**To Reproduce**
```
 # Validate app package using validation rules
 - uses: teamsApp/validateAppPackage
   with:
       # Relative path to this file. This is the path for built zip file.
       appPackagePath: ../../../apps/teams/dist/manifest-metaos/CopilotForSales_MetaOSAppPackage_local.zip

 # publish the app to the tenant app catalog
 # this is only a one-time operation that will throw an error "app with this id already exist" next time
 - uses: teamsApp/extendToM365
   with:
       appPackagePath: ../../../apps/teams/dist/manifest-metaos/CopilotForSales_MetaOSAppPackage_local.zip
   writeToEnvironmentFile:
      titleId: M365_TITLE_ID # Required. The ID of M365 title.
      appId: M365_APP_ID # Required. The app ID of M365 title.
```

**Expected behavior**
Command should run without error and deploy to https://admin.microsoft.com/#/Settings/IntegratedApps

Using VS teams toolkit **not** VS code
