### ISSUE TITLE
Script action environment output regexp is too strict and do not support whitespaces

### ISSUE THREAD

**Issue by alexanderbob** [OfficeDev/teams-toolkit#12102]
**Describe the bug**
[Regular expression](https://github.com/OfficeDev/teams-toolkit/blob/fde7aac5f4f3a23b91440fe5010c6eff679e1780/packages/fx-core/src/component/driver/script/scriptDriver.ts#L215) to parse teamsfx environment variables from script output is too strict and do not allow whitespaces or ' and " 
Was introduced in https://github.com/OfficeDev/teams-toolkit/pull/8811

**To Reproduce**
Run provisioning using the following yml file
```
version: 1.1.0

provision:
    - uses: script
      with:  
        run: "Write-Host ::set-teamsfx-env Test0=\"multi word variable\"
              Write-Host ::set-teamsfx-env Test1='multi word variable'
              Write-Host ::set-teamsfx-env Test2=multi+word+variable"
        shell: pwsh
```
**Current behavior**
Action script in lifecycle provision succeeded with output {"Test0":"multi","Test1":"multi","Test2":"multi+word+variable"}

**Expected behavior**
Test0 and Test1 variables in the output should both be "multi word variable"

**Screenshots**
![image](https://github.com/user-attachments/assets/08cef555-217c-4932-92e4-cfedbee6a207)
![image](https://github.com/user-attachments/assets/31183164-5576-4b35-a954-4d03ed051deb)
