### ISSUE TITLE
Getting error `Expected signal to be an instanceof AbortSignal.`

### ISSUE THREAD

**Issue by gabrielsanches** [OfficeDev/teams-toolkit#12560]
**Describe the bug**
When I try to deploy using new version v5.10 of the extension is breaking on azureStorage/deploy. I've downgraded to v5.8.2 and it works just fine.

**To Reproduce**
1. Click on `Deploy` option in Teams Toolkit.
2. Receiving error on third step (azureStorage/deploy)

**Expected behavior**
No error during deploy with new version v5.10

**VS Code Extension Information (please complete the following information):**
 - OS: Ubuntu 22.04.5
 - Version v5.10

**Additional context**
Here is my yaml to deploy, failing trying to deploy bits to azure storage.

```
deploy:
  # Run npm command
  - uses: cli/runNpmCommand
    with:
      args: install
  # Run npm command
  - uses: cli/runNpmCommand
    env:
      REACT_APP_CLIENT_ID: ${{AAD_APP_CLIENT_ID}}
      REACT_APP_START_LOGIN_PAGE_URL: ${{TAB_ENDPOINT}}/auth-start.html
      REACT_APP_FUNC_NAME: getUserProfile
    with:
      args: run build --if-present
  # Deploy bits to Azure Storage Static Website
  - uses: azureStorage/deploy
    with:
      # Deploy base folder. This folder includes manifest files for AAD app and Teams app that should be ignored using the ignoreFile.
      artifactFolder: build
      # The resource id of the cloud resource to be deployed to
      resourceId: ${{TAB_AZURE_STORAGE_RESOURCE_ID}}
```
