### ISSUE TITLE
Toolkit v5 support for Visual Studio/.Net

### ISSUE THREAD

**Issue by ashikns** [OfficeDev/teams-toolkit#8962]
**Is your feature request related to a problem? Please describe.**
I have been developing Teams app on Visual Studio + .Net Core. The latest documentation for toolkit only mentions support for Visual Studio Code.

**Describe the solution you'd like**
Is there any plan to bring the toolkit v5 update to Visual Studio? Or add support for C#/.Net Core in the Visual Studio Code version of the toolkit?

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ashikns** [comment]
I was able to get this working. The most important change was to the .yml files. Modify the `deploy` command like for dotnet instead of npm:
```
deploy:
  # Run dotnet command
  - uses: cli/runDotnetCommand
    with:
      args: publish /property:GenerateFullPaths=true

  # Generate runtime environment variables
  - uses: file/createOrUpdateJsonFile
    with:
      target: ./appsettings.Development.json
      appsettings:
        BOT_ID: ${{BOT_ID}}
        BOT_PASSWORD: ${{SECRET_BOT_PASSWORD}}
```
There are also a few adjustments needed to tasks.json and launch.json, but it's a little bit of "tweak it till it works" situation. Thanks for including the dotnet commands already on release, would love to see some official documentation as well.
